version: '3'
services:
  yacd:
    build: .
    image: yacd-meta
    container_name: yacd-meta
    restart: always
    ports:
      - "9090:80"
    environment:
      - YACD_DEFAULT_BACKEND=http://10.10.1.3
